using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UIElements;
using UnityEditor.Experimental.GraphView;
using UnityEditor;

namespace BehaviorTree
{
    public class NodeView : UnityEditor.Experimental.GraphView.Node
    {
        public Action<NodeView> OnNodeSelected;
        public Node node;
        public Port input;
        public List<Port> outputs = new List<Port>();

        public NodeView(Node node) : base("Assets/BehaviorTrees/Editor/UIBuilder/NodeView.uxml")
        {
            this.node = node;
            title = node.name;

            // metadata to retrieve node from graph view
            viewDataKey = node.guid;

            style.left = node.position.x;
            style.top = node.position.y;

            CreateInputPorts();
            CreateOutputPorts();
            SetupUXMLClasses();
        }

        private void SetupUXMLClasses()
        {
            if (node is Leaf)
            {
                AddToClassList("leaf");
            }
            else if (node is Control)
            {
                AddToClassList("control");
            }
            else if (node is Decorator)
            {
                AddToClassList("decorator");
            }
        }

        private void CreateInputPorts()
        {
            if (node is RootNode)
            {
                return;
            }

            input = InstantiatePort(Orientation.Horizontal, Direction.Input, Port.Capacity.Single, typeof(bool));

            // clear autogenerated name
            inputContainer.Add(input);
        }

        private void CreateOutputPorts()
        {
            if (node is Leaf)
            {
                return;
            }
            else if (node is Control)
            {
                Control control = node as Control;
                outputContainer.Add(new Button(() =>
                {
                    outputContainer.Add(InstantiatePort(Orientation.Horizontal, Direction.Output, Port.Capacity.Single, typeof(bool)));
                }));
                for (int i = 0; i < control.children.Count; i++)
                {
                    Port port = InstantiatePort(Orientation.Horizontal, Direction.Output, Port.Capacity.Single, typeof(bool));
                    outputs.Add(port);
                    outputContainer.Add(port);
                }
            }
            else
            {
                Port port = InstantiatePort(Orientation.Horizontal, Direction.Output, Port.Capacity.Single, typeof(bool));
                outputs.Add(port);
                outputContainer.Add(port);
            }

        }

        public override void SetPosition(Rect newPos)
        {
            base.SetPosition(newPos);
            Undo.RecordObject(node, "Behavior Tree (Change Position)");
            node.position.x = newPos.xMin;
            node.position.y = newPos.yMin;
            EditorUtility.SetDirty(node);
        }

        public override void OnSelected()
        {
            base.OnSelected();
            if (OnNodeSelected != null)
            {
                OnNodeSelected.Invoke(this);
            }
        }
    }
}